Login/Logout - Unit tests mobile (#97)
* Splash functionality was implemented. This applies with error data and not found data. Retrofit service was fixed for extracting info just for auth user. Some sonar issues were fixed.

* AuthViewModel unit test was created. Android libraries were updated.

* Unit test were added for viewmodel package. Several fixes were implemented according to unit tests.

* UI tests were added. Libraries were updated.

* Unit tests were updated. New strings were created.

* Gradle file was updated with jacoco library

* Test dispatcher was implemented to avoid conflict with workflow git actions

* Unit tests were updated to run on workflow

* Workflow updated.

* JaCoCo config was updated to fix coverage report path

* Workflow updated.

* Workflow updated.

* Workflow updated.

* Workflow updated.

* AndroidTest coverage was enabled

* Firebase support was added.

* Firebase support was fixed

* I18N and A11Y problems were fixed

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -39,15 +39,29 @@ jobs:
     - name: Setup Android SDK
       uses: android-actions/setup-android@v3
 
+    - name: Install xmllint
+      run: sudo apt-get install -y libxml2-utils
+
     - name: Run Unit Tests
       run: ./gradlew testDebugUnitTest jacocoTestReport
+
+    - name: Check if JaCoCo report exists
+      if: success()
+      run: |
+        if [ ! -f app/build/reports/jacoco/testDebugUnitTest/jacocoTestReport.xml ]; then
+          echo "JaCoCo report not found in mobile/app/build/reports/jacoco/testDebugUnitTest!"
+          exit 1
+        else
+          echo "JaCoCo report found in mobile/app/build/reports/jacoco/testDebugUnitTest."
+        fi
+      continue-on-error: false
 
     - name: Verify Coverage
       if: success()
       run: |
         # Calcula la cobertura de los ViewModels a partir del archivo XML de JaCoCo
-        COVERAGE=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@covered)" build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
-        MISSED=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@missed)" build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
+        COVERAGE=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@covered)" app/build/reports/jacoco/testDebugUnitTest/jacocoTestReport.xml)
+        MISSED=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@missed)" app/build/reports/jacoco/testDebugUnitTest/jacocoTestReport.xml)
         TOTAL=$((COVERAGE + MISSED))
         PERCENT=$((COVERAGE * 100 / TOTAL))
         echo "Line Coverage for ViewModels: $PERCENT%"
