Update mobile pipelines

diff --git a/.github/workflows/mb_manual_unit_testing.yml b/.github/workflows/mb_manual_unit_testing.yml
--- a/.github/workflows/mb_manual_unit_testing.yml
+++ b/.github/workflows/mb_manual_unit_testing.yml
@@ -48,12 +48,23 @@ jobs:
     - name: Run Unit Tests
       run: ./gradlew testDebugUnitTest jacocoTestReport
 
+    - name: Check if JaCoCo report exists
+      if: success()
+      run: |
+        if [ ! -f app/build/reports/jacoco/testDebugUnitTest/jacocoTestReport.xml ]; then
+          echo "JaCoCo report not found in mobile/app/build/reports/jacoco/testDebugUnitTest!"
+          exit 1
+        else
+          echo "JaCoCo report found in mobile/app/build/reports/jacoco/testDebugUnitTest."
+        fi
+      continue-on-error: false
+
     - name: Verify Coverage
       if: success()
       run: |
         # Calcula la cobertura de los ViewModels a partir del archivo XML de JaCoCo
-        COVERAGE=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@covered)" build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
-        MISSED=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@missed)" build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
+        COVERAGE=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@covered)" app/build/reports/jacoco/testDebugUnitTest/jacocoTestReport.xml)
+        MISSED=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@missed)" app/build/reports/jacoco/testDebugUnitTest/jacocoTestReport.xml)
         TOTAL=$((COVERAGE + MISSED))
         PERCENT=$((COVERAGE * 100 / TOTAL))
         echo "Line Coverage for ViewModels: $PERCENT%"
@@ -62,3 +73,4 @@ jobs:
           exit 1
         fi
       continue-on-error: false
+  
